version: '3.8'

services:
  backend:
    build: ./ServiceBookingSystem
    container_name: car-rental-backend
    network_mode: "host"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/service_booking_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin13
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  frontend:
    build: ./ServiceBookingWeb
    container_name: car-rental-frontend
    # 👇 Changed from host mode to explicit port 8081 mapping to bypass native blocks
    ports:
      - "8081:80"
    depends_on:
      - backend
